USE gwandro_BGT;

CREATE TABLE Certs
	SELECT * FROM BGT_CLASS.Certs;
    
CREATE TABLE Counties
	SELECT * FROM BGT_CLASS.Counties;
    
CREATE TABLE Degrees
	SELECT * FROM BGT_CLASS.Degrees;
    
CREATE TABLE Exp_Levels
	SELECT * FROM BGT_CLASS.Exp_Levels;
    
CREATE TABLE Jobs
	SELECT * FROM BGT_CLASS.Jobs;
    
CREATE TABLE Jobs_Certs
	SELECT * FROM BGT_CLASS.Jobs_Certs;
    
CREATE TABLE Jobs_Degrees
	SELECT * FROM BGT_CLASS.Jobs_Degrees;
    
CREATE TABLE Jobs_Majors
	SELECT * FROM BGT_CLASS.Jobs_Majors;
    
CREATE TABLE Jobs_Skills
	SELECT * FROM BGT_CLASS.Jobs_Skills;
    
CREATE TABLE Majors
	SELECT * FROM BGT_CLASS.Majors;
    
CREATE TABLE MSAs
	SELECT * FROM BGT_CLASS.MSAs;
    
CREATE TABLE Occupations
	SELECT * FROM BGT_CLASS.Occupations;
    
CREATE TABLE RECORDS
	SELECT * FROM BGT_CLASS.RECORDS;
    
CREATE TABLE Skills
	SELECT * FROM BT_CLASS.Skills;
    
CREATE TABLE States
	SELECT * FROM BGT_CLASS.States;
    
CREATE TABLE States
	SELECT * FROM BGT_CLASS.States;
        
CREATE TABLE Titles
	SELECT * FROM BGT_CLASS.Titles;
    
